
<!DOCTYPE html>
<html class="client-nojs" lang="en" dir="ltr">
<head>

<title>Yamai Devi, Rashin Ahmednagar - Wikipedia</title>
</head>
<body bgcolor="#e1f3f5">
<div align=\"right\">
<p><a href="temple.php"><font color="red" size=5><b>Back</b></font></a></p>
<p align="center" >
<font size="+7"><img src="../images/20161202100614.jpg" width="346" height="269" align="left"><em> Jagdamba Temple  Rashin</em></font>
<font size="+6"><img src="../images/20161202100308.jpg" width="316" height="261" align="right"></font>
<p >

<p >The Jagdamba Mata temple in Rashin comes in the Taluka Karjat in the district of Ahmednagar. The temple is to the east of  at a distance of 114&#160;km. This is a very ancient temple well known for the Yamai and Tukai Deity, the Avatar Swarup of Mata Renuka. Rashin Devi is the Kuldevta of many people in Maharashtra. At present no known and detailed scripts or books are available giving more information of the place except for the locally published book in Marathi known as the "Shri Jagdamba Mata Rashin Charitra" which has been formulated by the devi bhaktas in Rashin. This book is available at Rashin with the Gurav Pujari of Rashin. As mentioned in the book, the legend behind the sthapana of the devi mandir in Rashin goes like this.
<p>As per the original legend in the Skanda Puran our beloved earth mother was being ruled over by dytyas and unholy powers. Everywhere it was the rule of adharm, torture and brutal killings of innocent people. Even the gods in the heaven were left helpless and powerless over the situation. With the rule of the daityas there was no faith, no sadachar rather the Brahmins, innocents creatures, and beings were made to live a miserable torturous life. The mukya diatya among these was the daitya named "Rakta Beej".</p>
<p>Rakta Beej had a special boon from Bhagwan Shankar, due to which he became more powerful and was misusing his powers by causing harm to everyone. His place of ruling was in Rashin where he caused more harm and trouble. Everyone residing in Rashin was helpless and could not do anything about this unjust ruling. Nobody dared to put up resistance against Rakta Beej, and feared for their lives. Even Harihar (Vishnu &amp; Shankar) were not powerful enough to conquer Rakta Beej. Hence as a solution all the devas started praying to Jugdamba Mata.</p>
<p>All the gods and rushi munis prayed to the adimata shakti to uplift them and protect them from Rakta Beej. "O' Goddess O' Mother please relieve us from the torture and suffering caused by Rakta Beej. We pray to thee as you are our saviour our mother please hear our prayers and relieve us from our sorrow and suffering. Hey Vishnu Shakti hey durga devi please relieve us from our troubles and give us your protection and safety".</p>
<p>Hearing their prayers Ma Jugdamba was very pleased. She spoke to them, "Whenever this world will be troubled and tortured by unholy powers and daityas, during that every time I will take Avatar to relieve this world and all the beings of this world from those unholy powers". As the goddess was pleased, she descended as Devi Yamai, from the pawan skhetra of Tuljapur. Ma Tuljabhavani of Tuljapur took the Avatar in Rashin of Devi Yamai and so began the battle between the goddess and the daitya Rakta Beej. In the ferocious battle there was a big heap of the corpses of the daityas but still the diatyas weren't being outnumbered. There were more and more of them. Seeing this situation the devas and the rushi munis prayed Ma Renuka of Mahurgad to come and assist Devi Yamai. That's when Devi Renuka of Mahurgad took the Avatar of Ma Tukai.</p>
<p>Rakta Beej ignored the akash vani and in his own sense of arrogance went on to fight the devis. Once again the voice in the sky warned the daitya, "Do not commit the mistake of fighting the devis, still you have time to seek their ashirvaad and back out from the battle". But the daitya ignored the warning and went on to battle with his full strength. The battle scene was full of so much action and breathtaking, even I do not have the right words to describe it. Who can stand against the ultimate shakti, who can face the mahishasur Mardnini, the shumbha Nishumbha tarini. All the gods and rushi munis prayed to the goddess for protection in full strength. The devi answered their prayers. She killed the daitya and liberated the earth, liberated Rashin from the evil daitya.</p>
<p>That's when the Gods and the Rushi Munis prayed the Devi again. "O devi O Shumbha Nishumbha Mardini Riding the lion you killed Mahishasura you took upon the Kalika Avatar and you killed chanda Munda and took upon the name Chamunda You killed the Rakhta Beej we bow before you. We are grateful to you. Jay Ma Ambe Jay Ma Ambe".</p>
<p>Now only Sudrik the minister of Rakta Beej was left. Devi Yamai, threw her weapon upon the left over demons and they were converted into beautiful Lotuses. A rope was tied around the neck of sudrik and he was made to stand in front of the Devi. The devi looked upon him and manifested her Avatar of Adimaya to him. Seeing her Virat Rupa Sudrik was mesmerised in a trance. He took sharan of the devi and prayed to her "O devi forgive me, please save me. You are the greatest power of all the powers in the world, please forgive me. I bow down to your virat Rudra Rupa. This world the entire tribhuvan is your play ground. I deserve to be punished, but please forgive me, please protect me. I will stay wherever you order me to stay, will eat whatever you give me to eat, will live the way you order me to live. I will become your humble servant and serve you. I am a sinned creature, but there is nobody else apart from you whom I can pray for my liberation and well being. Apart from you I have no other protector and saviour. I cannot go anywhere leaving your lotus feet. " Listening to these humble words of Sudrik, Devi Yamai took a motherly rupa, she felt content and satisfied at his words. She asked him to go back to his land as a protector of his place. He became like a guard on duty, a guard who protects and takes care of his place. That's why there is a temple on the east of Rashin of Sudrik. All the Bhaktas of Rashin, take his darshan and become purified of their sins just like Sudrik became cleansed of all his sins.</p>
<p>This is the importance of the Rashin skhetra. Mata Yamai and Tukai both reside here to protect and liberate their Bhaktas from all their sins.</p>
<h2><span class="mw-headline" id="Temple_routine">Temple routine</span></h2>
<p>The entire temple is cleansed and washed every month. The Nitya Pooja of the devi is done two times in the day. The temple Mahadvars open 4 am. Current Temple Pujari is Arun Sadashiv Renukar (Gurav). Gurav pujari performs the morning pooja, and wakes up the devi from her sleep. He bathes the devi with yogurt, milk, honey panchamrut. Then he decorates the deity with a beautiful mahavastra. He beautifies her forehead with chandan. Offers her haldi and kumkum. Every day he garlands her with flowers. During the kakad arti in the morning and the aarti during the night before the deity sleeps, the pujari offers her a Every businessman of rashin starts his works after the yamai devies darshan and by taking pavitra prashad.to the east of yamai mata mandir thetre is a temple of laxmi mata mandir at Karmala, dist solapur and at west there is the temple of lord ganesha ( siddhi vinayak, sidhatek). The real birthplace of jugdambaa was kuldharan nearly 20&#160;km from rashin</p>
<h2>&nbsp;</h2>
</body>
</html>
