<html>
<body bgcolor="#e1f3f5">


<div align=\"right\"><a href="school.php"><font color="red" size=5><b>Back</b></font></a>
  <div class="main"><div class="head-bg"><h1 class="school_title center">New Gurukul English School Karjat <small>Ahmadnagar, Maharashtra</small></h1>
</div>
  <hr><div class="row"><div class="col-md-6"><h4 style="margin-top:0"><i class="fa fa-map-marker"></i></h4></div></div><div class="row"></div>
  <div class="jumbotron"><script async="" src="./New Gurukul English School Karjat, Karjat, Ahmadnagar - Maharashtra_files/adsbygoogle.js.download"></script>
    <script>(adsbygoogle = window.adsbygoogle || []).push({});</script><br><div class="table-responsive"><table class="table table-striped table-hover toprint"><tbody><tr><th scope="row">School Name</th><td style="color:#f39c12" class="fa fa-university fa-2x"></td><td class="tfield"><strong itemprop="name">New Gurukul English School Karjat</strong></td></tr><tr><th scope="row">Address</th><td style="color:#f39c12" class="fa fa-map-marker fa-2x"></td><td class="tfield" itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress"><span itemprop="streetAddress">Karjat, Ahmadnagar, Maharashtra, Postal Code: 414402 India</span></td></tr><tr><th scope="row">Cluster Name</th><td style="color:#2980b9" class="fa fa-location-arrow fa-2x"></td><td class="tfield">Karjat</td></tr><tr><th scope="row">Block Name</th><td style="color:#3498db" class="fa fa-compass fa-2x"></td><td class="tfield">Karjat</td></tr><tr><th scope="row">School Type</th><td style="color:#8e44ad" class="fa fa-group fa-2x"></td><td class="tfield">Co-Educational</td></tr><tr><th scope="row">School Category</th><td style="color:#8e44ad" class="fa fa-graduation-cap fa-2x"></td><td class="tfield">Primary Only</td></tr><tr><th scope="row">School Head Master</th><td style="color:#16a085" class="fa fa-user fa-2x"></td><td class="tfield">Gangarde Satish Prakash</td></tr><tr><th scope="row">School Management</th><td style="color:#9b59b6" class="fa fa-sitemap fa-2x"></td><td class="tfield">Private Un-Aided</td></tr><tr><th scope="row">Mid-Day Meal</th><td style="color:#9b59b6" class="fa fa-cutlery fa-2x"></td><td class="tfield">Not Applicable</td></tr><tr><th scope="row">Medium of Instruction</th><td style="color:#3498db" class="fa fa-language fa-2x"></td><td class="tfield">English</td></tr><tr><th scope="row">Founded In Year</th><td style="color:#8e44ad" class="fa fa-calendar fa-2x"></td><td class="tfield">2013</td></tr><tr><th scope="row">Location Type</th><td style="color:#f1c40f" class="fa fa-tree fa-2x"></td><td class="tfield">Rural</td></tr><tr><th scope="row">School Building Type</th><td style="color:#f1c40f" class="fa fa-building fa-2x"></td><td class="tfield">Private Building</td></tr><tr>
      <th scope="row">No. of Books in Library </th><td style="color:#2ecc71" class="fa fa-book fa-2x"></td><td class="tfield">667</td></tr><tr>
        <th scope="row">No. of Computers </th><td style="color:#9b59b6" class="fa fa-desktop fa-2x"></td><td class="tfield">11</td></tr><tr>
          <th scope="row">No. of Class Rooms </th><td style="color:#8e44ad" class="fa fa-simplybuilt fa-2x"></td><td class="tfield">2</td></tr><tr>
            <th scope="row">No. of Teachers </th><td style="color:#e67e22" class="fa fa-group fa-2x"></td><td class="tfield">2</td></tr><tr><th scope="row">Classes</th><td style="color:#1abc9c" class="fa fa-cube fa-2x"></td><td class="tfield">Class 1 to 5</td></tr><tr><th scope="row">Drinking Water Type</th><td style="color:#e74c3c" class="fa fa-tint fa-2x"></td><td class="tfield">Other than Hand-Pump/Tube-Well/Tap Water</td></tr></tbody></table>
   
<script>(adsbygoogle = window.adsbygoogle || []).push({});</script><br>NOTE: The data available with us about New Gurukul English School Karjat is maintained by the 'National University of Educational Planning and Administration' under the program 'District Information System for Education 2013-2014'. If you're looking for more details regarding admission/application forms, fees, school timings, vacations/holidays schedule or facilities provided, kindly visit the relevant department of the school.</div>  </div>  </div></div>
<link rel="stylesheet" type="text/css" href="./New Gurukul English School Karjat, Karjat, Ahmadnagar - Maharashtra_files/font-awesome.min.css"><script src="./New Gurukul English School Karjat, Karjat, Ahmadnagar - Maharashtra_files/api.js.download" async="" defer=""></script><script src="./New Gurukul English School Karjat, Karjat, Ahmadnagar - Maharashtra_files/script.js.download"></script><script type="text/javascript">/* <![CDATA[ */(function(d,s,a,i,j,r,l,m,t){try{l=d.getElementsByTagName('a');t=d.createElement('textarea');for(i=0;l.length-i;i++){try{a=l[i].href;s=a.indexOf('/cdn-cgi/l/email-protection');m=a.length;if(a&&s>-1&&m>28){j=28+s;s='';if(j<m){r='0x'+a.substr(j,2)|0;for(j+=2;j<m&&a.charAt(j)!='X';j+=2)s+='%'+('0'+('0x'+a.substr(j,2)^r).toString(16)).slice(-2);j++;s=decodeURIComponent(s)+a.substr(j,m-j)}t.innerHTML=s.replace(/</g,'&lt;').replace(/>/g,'&gt;');l[i].href='mailto:'+t.value}}catch(e){}}}catch(e){}})(document);/* ]]> */</script><script> (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,'script','//www.google-analytics.com/analytics.js','ga'); ga('create', 'UA-32008075-5', 'auto'); ga('send', 'pageview');</script><script type="text/javascript" src="./New Gurukul English School Karjat, Karjat, Ahmadnagar - Maharashtra_files/js"></script></body></html>
